FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /server ./cmd/api

FROM alpine:3.20
COPY --from=build /server /server
ENV PORT=8080
EXPOSE 8080
CMD ["/server"]
